name: Deploy to Server (Self-Hosted)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    # EN ÖNEMLİ DEĞİŞİKLİK: GitHub'ın makinesi yerine kendi agent'ımızı kullan diyoruz.
    runs-on: self-hosted

    steps:
    # Adım 1: Sunucuda direkt komutları çalıştır (SSH'a gerek yok)
    - name: Kodu Güncelle
      run: |
        echo "Deployment basliyor..."
        cd /var/www/test-projesi
        echo "Proje klasorune girildi."
        git pull origin main
        echo "Guncellemeler GitHub'dan cekildi."
        echo "Deployment tamamlandi!"
